DROP DATABASE IF EXISTS typing_db;
CREATE DATABASE typing_db;

CREATE TABLE user (
    username VARCHAR(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    score INT
);
CREATE TABLE english (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prompt TEXT 
);
CREATE TABLE javascript (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prompt TEXT 
);
CREATE TABLE html (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prompt TEXT 
);
CREATE TABLE css (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    prompt TEXT 
);
